### ISSUE TITLE
Uncaught Error: Cannot find module "material-ui/lib/app-bar"

### ISSUE THREAD

**Issue by smandava** [Microsoft/vscode-react-sample#2]
Npm install ran Ok but Browser is throwing Cannot find module "material-ui/lib/app-bar" error at 

App.js
import AppBar from 'material-ui/lib/app-bar';

Any idea how fix this? 

-Thanks

**Comment by smandava** [comment]
Changing
`import AppBar from 'material-ui/lib/app-bar';`
to
`import AppBar from 'material-ui/AppBar';`

Fixes the problem. material ui might have changed the paths..

**Comment by waderyan** [comment]
Interesting...
