### ISSUE TITLE
Backend should be npm run serve

### ISSUE THREAD

**Issue by coolegos** [Microsoft/vscode-react-sample#4]
`npm ERR! missing script: server`

**Comment by KrisvanderMast** [comment]
I made a pull request, currently pending, to fix this. Also found out about the server vs serve mistyping in the readme file and found the alternative to press the F5 key not clear enough so also updated that. Pull request can be seen here: https://github.com/Microsoft/vscode-react-sample/pull/5.

**Comment by waderyan** [comment]
Looks great! Thanks
